Reduce the severity of auxilliary vector errors and fail safe
frida/glib pull request #7
Opened 2020-04-15 13:22 UTC by WorksButNotTested

Workaround for auxilliary vector failures when running 32-bit code on a 64-bit kernel.

2020-04-15 18:35 UTC, oleavr requested changes
Thanks! :tada:

2020-04-15 18:35 UTC, oleavr commented on glib/gutils.c
> +     * auxilliary vector can unreliable, likely as a result of the vector not
```suggestion
     * auxilliary vector can be unreliable, likely as a result of the vector not
```

2020-04-15 18:35 UTC, oleavr commented on glib/gutils.c
> +     * was setuid). Hence we assume the worst case scenario.
```suggestion
```

I think we can just swallow the error to avoid noise.

2020-04-15 18:35 UTC, oleavr commented on glib/gutils.c
> +    g_warning ("getauxval () failed: %s", g_strerror (errsv));
```suggestion
```

2020-04-15 18:35 UTC, oleavr commented on glib/gutils.c
> +    return TRUE;
```suggestion
    return FALSE;
```

Seems like a better failure mode would be `FALSE` here.

2020-04-15 18:35 UTC, oleavr commented on glib/gutils.c
> +  {
```suggestion
    {
```

2020-04-15 18:35 UTC, oleavr commented on glib/gutils.c
> +    /* When running 32-bit user applications on a 64-bit kernel, reading of the
(Indentation must be adjusted to account for the block being added.)

2020-04-15 18:35 UTC, oleavr commented on glib/gutils.c
> +  }
```suggestion
    }
```

2020-04-16 11:03 UTC, WorksButNotTested commented on glib/gutils.c
> +     * was setuid). Hence we assume the worst case scenario.
Happy to go whichever way you like. But this was my logic for how I decided how to make the change.

This check determines whether the application is running setuid. More generally, this is used for things like not trusting the user environment so as to avoid setuid programs from being exploited by malicious input to gain a priv esc. The value of TRUE returned here means that the app is setuid and hence should be subject to additional restrictions to avoid these types of issues.

Hence, by returning TRUE here, even though our application is not likely to be running setuid we ensure we don't compromise security. We do have the potential by introducing these restrictions that it may have some impact on functionality, however, but I have not come across any problems despite using a hack like this for some time (albeit my use cases may not be representative of others and I may not be using all features). I left the warning here to alert people should they encounter any issues as a result. I figured that it wouldn't cause too much noise as it is only a one-liner and the message should only appear when running 32-bit code on 64-bit platforms (which shouldn't affect many users, if others were commonly doing this then this issue would have been a show-stopper and they might have fixed it already).

I accept that FRIDA is unlikely to be used on production systems (except a for few very adventurous people) and therefore perhaps security may not be of critical importance, but given I didn't understand the impact of the change, I felt more comfortable to err on the side of caution.

One could argue that if we were to assume that the program is not running setuid root if we encounter a failure condition (e.g. we fail open) then the check could simply be excluded all together?

As I said, I'm happy to go with whatever direction you like. I'm just happy if I get it working for my purposes without introducing regressions for others.

2020-04-16 18:54 UTC, oleavr commented on glib/gutils.c
> +     * was setuid). Hence we assume the worst case scenario.
Ahh yes of course that's what it's used for. Totally agree with your reasoning. Let's go with `TRUE` as it was. I think we can omit the warning though, as this is going to happen every time in certain environments.

2020-04-17 00:10 UTC, WorksButNotTested commented
Changed to remove warning message as suggested.

2020-04-17 00:41 UTC, merged